branches:
  only:
    - master
    # travis testing branches
    - /^travis/
    # version tags (from https://github.com/sindresorhus/semver-regex)
    - /^v?(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[\da-z\-]+(?:\.[\da-z\-]+)*)?(?:\+[\da-z\-]+(?:\.[\da-z\-]+)*)?$/

sudo: false
dist: trusty
language: node_js
node_js: 8
install: npm install

matrix:
  include:
    - script:
        - npm run lint
 
    - script:
        - npm run test -- --coverage --runInBand
        - npm run flow -- check
      after_success:
        - ./node_modules/.bin/coveralls < ./coverage/lcov.info
        - bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json

    - script:
        - npm run build
