# NOTE: This file must use spaces. Travis won't read it otherwise.

# Opt-in to the new Travis infrastructure
sudo: false

# Cache node_modules
cache:
  directories:
    - $HOME/.npm
    - node_modules

# Send travis notifications to Slack
notifications:
  slack:
    secure: iNz4CfNIkTXwl7G71nTgLMXUKKYMqQJkvQKuBck33Eg+tFy/w6O3bMEyGLdfJZKHO0Q3fE/Wbw+SIp77TBG4i/YQ87/cQWnFv21temZoBnkYPk5IiusUR/5AJPCpFJSnDlB92XDGz06ilL1oFW6R3yGjn5lUqUDy2a+Pj0TUp1w=

language: node_js

branches:
  only: [master, stable, /^travis/]

node_js:
  - stable

# run each command in parallel
env:
  - CMD=lint
  - CMD=run-coverage
  - CMD=build-ci

script:
  - if [[ $CMD = "cover" ]]; then npm install coveralls codecov; fi
  - npm run $CMD

after_success: npm run coveralls; npm run codecov
