# NOTE: This file must use spaces. Travis won't read it otherwise.

# Opt-in to the new Travis infrastructure
sudo: false

# Send travis notifications to Slack
notifications:
  slack:
    secure: iNz4CfNIkTXwl7G71nTgLMXUKKYMqQJkvQKuBck33Eg+tFy/w6O3bMEyGLdfJZKHO0Q3fE/Wbw+SIp77TBG4i/YQ87/cQWnFv21temZoBnkYPk5IiusUR/5AJPCpFJSnDlB92XDGz06ilL1oFW6R3yGjn5lUqUDy2a+Pj0TUp1w=

# Activate SauceLabs
# env:
#   global:
#     - secure: VCpPSopc+qroGDxXtn6gS/NjPPYpo8FQoF3Pt29upF98KXBsbYhSj5DUTZX/aVVfHa4LAUFxR6UnrxfBO0ygspTnQ4J42w6uaUtdeKYm6MXRjHZEmFiNYj13xvmHnq+37FRMXMdO0QPzYLx2MxryUW/OksNax+BxfsvYcsSCevw=
#     - secure: ixYxBb+hx10o19eTCCXidSZ2G7pMDpqgfM3tSla3CcMyGUOpb+GUjh4mE8ExCbrJVzgfNLyJJXmrhzJNP6Vkaa7JFglzjgytzIDQiLNMVOvT4xrT6Niu1+3XrcucfGsc0tlXcNTWs3GeNyc3FgacABNAocAquhBKtz6gnGkpVn4=

# addons:
#   sauce_connect: true


language: node_js

branches:
  only: [master, stable]

node_js:
  - "0.10.31"
  - stable


# Be sure to install npm@3 before calling "npm install"
before_install:
  - npm install -g npm@3

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - echo 'Linting…' && echo -en 'travis_fold:start:script.1\\r'
  - npm run lint
  - echo -en 'travis_fold:end:script.1\\r'

  - echo 'Building areas…' && echo -en 'travis_fold:start:script.1\\r'
  - npm run build:areas
  - echo -en 'travis_fold:end:script.1\\r'

  - echo 'Testing students…' && echo -en 'travis_fold:start:script.1\\r'
  - npm run test:students
  - echo -en 'travis_fold:end:script.1\\r'

  - echo 'Testing Karma…' && echo -en 'travis_fold:start:script.1\\r'
  - npm run karma:ci
  - echo -en 'travis_fold:end:script.1\\r'

  - echo 'Building…' && echo -en 'travis_fold:start:script.1\\r'
  - npm run build:ci
  - echo -en 'travis_fold:end:script.1\\r'

after_success: npm run coveralls
